site_name: unblob - extract everything!
site_author: ONEKEY developers
site_description: unblob is an accurate, fast, and easy-to-use extraction suite. unblob parses unknown binary blobs for more than 30 different archive, compression, and file-system formats, extracts their content recursively, and carves out unknown chunks that have not been accounted for. This turns unblob into the perfect companion for extracting, analyzing, and reverse engineering firmware images.
site_url: https://unblob.org/

repo_name: Unblob on GitHub
repo_url: https://github.com/onekey-sec/unblob
edit_uri: ""

nav:
  - About: index.md
  - User Guide: guide.md
  - installation.md
  - formats.md
  - extractors.md
  - development.md
  - API: api.md
  - glossary.md
  - publications.md
  - support.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.magiclink
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  logo: logo.svg
  favicon: favicon.png
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs

extra_css:
  - extra.css

plugins:
  - search
  - mkdocstrings
  - social:
      cards: true
      cards_color:
        fill: "#002060"
        text: "#00FFC8"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onekey-sec/unblob
      name: unblob on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/onekey_sec
      name: ONEKEY on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/onekey-sec/
      name: ONEKEY on LinkedIn
  analytics:
    provider: google
    property: G-RQC2V8NDHT
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2021 - 2025 ONEKEY GmbH.
  | <a href="/privacy/">Privacy policy</a>
  | <a href="#__consent">Change cookie settings</a>
