name: Documentation

on:
  push:
    branches:
      - main
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.9"

      - name: Install the project
        run: uv sync --only-group docs

      - name: Generate documentation
        run: uv run mkdocs gh-deploy --force
